---
title: "Presentation with Plotly"
author: "Raphael Moline"
date: "07/07/2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Plotly assignment

This is an assignment to create a web page presentation using R Markdown that features a plot created with Plotly


- first a graph using plot
- second a graph using ggplot2

## create Plot: diamonds data set, color by cut

```{r diamonds, echo=FALSE, message = FALSE}
library(ggplot2)
library(dplyr)
library(plotly)
diamonds <- filter(diamonds, clarity %in% c( "I1","IF","VS1")) %>%
    select(c(carat, cut,color,clarity, price))
diamonds <- diamonds[sample(nrow(diamonds), 1000),]
plot_ly(diamonds, x = ~carat, y = ~ price, mode = "markers", color = ~cut )
```

## use ggplot2: high / medium / low quality by cut

```{r echo=FALSE, message=FALSE}
p <- ggplot(data = diamonds, aes(x = carat, y = price, color = clarity))  +
    geom_point() + facet_wrap( ~ cut) 
    (gg <- ggplotly(p))
```
